"""Add mac_address to equipos

Revision ID: 41d35d73683b
Revises: 
Create Date: 2026-04-16 11:11:59.922645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d35d73683b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_device_id'), 'api_keys', ['device_id'], unique=True)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_usuario_id'), 'audit_logs', ['usuario_id'], unique=False)
    op.add_column('equipos', sa.Column('descripcion', sa.String(length=255), nullable=False))
    op.add_column('equipos', sa.Column('mac_address', sa.String(length=17), nullable=True))
    op.add_column('equipos', sa.Column('organizacion_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_equipos_mac_address'), 'equipos', ['mac_address'], unique=True)
    op.create_index(op.f('ix_equipos_organizacion_id'), 'equipos', ['organizacion_id'], unique=False)
    op.add_column('mantenciones', sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mantenciones', sa.Column('fecha_ejecucion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('avatar', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('usuarios', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('onboarding_step', sa.Integer(), nullable=True, comment='Paso actual del wizard (1-5), null si completado'))
    op.add_column('usuarios', sa.Column('onboarding_completed', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'onboarding_completed')
    op.drop_column('usuarios', 'onboarding_step')
    op.drop_column('usuarios', 'password_changed_at')
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'avatar')
    op.drop_column('usuarios', 'telefono')
    op.drop_column('mantenciones', 'fecha_ejecucion')
    op.drop_column('mantenciones', 'fecha_programada')
    op.drop_index(op.f('ix_equipos_organizacion_id'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_mac_address'), table_name='equipos')
    op.drop_column('equipos', 'organizacion_id')
    op.drop_column('equipos', 'mac_address')
    op.drop_column('equipos', 'descripcion')
    op.drop_index(op.f('ix_audit_logs_usuario_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_device_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
