#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_ENV_FILE="$ROOT_DIR/.env"
BACKEND_ENV_FILE="$ROOT_DIR/backend/.env"

generate_local_secret() {
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import secrets; print(secrets.token_urlsafe(24))'
    return
  fi

  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi

  printf '%s\n' "No se encontró python3 ni openssl para generar secretos locales." >&2
  return 1
}

read_env_value() {
  local file_path="$1"
  local key="$2"

  if [ -f "$file_path" ]; then
    awk -F= -v wanted_key="$key" '$1 == wanted_key {sub(/^[^=]*=/, ""); print; exit}' "$file_path"
  fi
}

EXISTING_MYSQL_PASSWORD="$(read_env_value "$ROOT_ENV_FILE" "MYSQL_ROOT_PASSWORD")"
EXISTING_MQTT_PASSWORD="$(read_env_value "$ROOT_ENV_FILE" "MQTT_PASSWORD")"
EXISTING_ROOT_SECRET_KEY="$(read_env_value "$ROOT_ENV_FILE" "SECRET_KEY")"
EXISTING_REDIS_PASSWORD="$(read_env_value "$ROOT_ENV_FILE" "REDIS_PASSWORD")"
EXISTING_SECRET_KEY="$(read_env_value "$BACKEND_ENV_FILE" "SECRET_KEY")"
EXISTING_ADMIN_PASSWORD="$(read_env_value "$BACKEND_ENV_FILE" "SEED_ADMIN_PASSWORD")"
EXISTING_TECNICO_PASSWORD="$(read_env_value "$BACKEND_ENV_FILE" "SEED_TECNICO_PASSWORD")"
EXISTING_DEMO_PASSWORD="$(read_env_value "$BACKEND_ENV_FILE" "SEED_DEMO_PASSWORD")"

LOCAL_MYSQL_PASSWORD="${MYSQL_ROOT_PASSWORD:-${EXISTING_MYSQL_PASSWORD:-$(generate_local_secret)}}"
LOCAL_MQTT_PASSWORD="${MQTT_PASSWORD:-${EXISTING_MQTT_PASSWORD:-$(generate_local_secret)}}"
LOCAL_SECRET_KEY="${SECRET_KEY:-${EXISTING_ROOT_SECRET_KEY:-${EXISTING_SECRET_KEY:-$(generate_local_secret)}}}"
LOCAL_REDIS_PASSWORD="${REDIS_PASSWORD:-${EXISTING_REDIS_PASSWORD:-$(generate_local_secret)}}"
LOCAL_SEED_ADMIN_PASSWORD="${SEED_ADMIN_PASSWORD:-${EXISTING_ADMIN_PASSWORD:-$(generate_local_secret)}}"
LOCAL_SEED_TECNICO_PASSWORD="${SEED_TECNICO_PASSWORD:-${EXISTING_TECNICO_PASSWORD:-$(generate_local_secret)}}"
LOCAL_SEED_DEMO_PASSWORD="${SEED_DEMO_PASSWORD:-${EXISTING_DEMO_PASSWORD:-$(generate_local_secret)}}"

ensure_env_key() {
  local file_path="$1"
  local key="$2"
  local value="$3"

  if ! grep -qE "^${key}=" "$file_path"; then
    printf '%s=%s\n' "$key" "$value" >> "$file_path"
  fi
}

create_root_env() {
  cat > "$ROOT_ENV_FILE" <<EOF
# Entorno local/demo generado automáticamente.
MYSQL_ROOT_PASSWORD=${LOCAL_MYSQL_PASSWORD}
MYSQL_DATABASE=${MYSQL_DATABASE:-manttoai_db}
MQTT_USERNAME=${MQTT_USERNAME:-manttoai_mqtt}
MQTT_PASSWORD=${LOCAL_MQTT_PASSWORD}
SECRET_KEY=${LOCAL_SECRET_KEY}
REDIS_PASSWORD=${LOCAL_REDIS_PASSWORD}
SEED_ADMIN_PASSWORD=${LOCAL_SEED_ADMIN_PASSWORD}
SEED_TECNICO_PASSWORD=${LOCAL_SEED_TECNICO_PASSWORD}
SEED_DEMO_PASSWORD=${LOCAL_SEED_DEMO_PASSWORD}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-manttoai}
EOF
}

create_backend_env() {
  cat > "$BACKEND_ENV_FILE" <<EOF
APP_NAME=ManttoAI Predictive Maintenance API
APP_ENV=${APP_ENV:-development}
API_PREFIX=
DATABASE_URL=${DATABASE_URL:-mysql+pymysql://root:${LOCAL_MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE:-manttoai_db}}
DATABASE_AUTO_INIT=${DATABASE_AUTO_INIT:-true}
SECRET_KEY=${LOCAL_SECRET_KEY}
MQTT_BROKER_HOST=${MQTT_BROKER_HOST:-mosquitto}
MQTT_BROKER_PORT=${MQTT_BROKER_PORT:-1883}
MQTT_USERNAME=${MQTT_USERNAME:-manttoai_mqtt}
MQTT_PASSWORD=${LOCAL_MQTT_PASSWORD}
MQTT_TELEMETRY_TOPIC=${MQTT_TELEMETRY_TOPIC:-manttoai/telemetria}
MQTT_ENABLED=${MQTT_ENABLED:-true}
SIMULATOR_ENABLED=${SIMULATOR_ENABLED:-false}
SIMULATOR_INTERVAL_SECONDS=${SIMULATOR_INTERVAL_SECONDS:-30}
SMTP_HOST=${SMTP_HOST:-mailpit}
SMTP_PORT=${SMTP_PORT:-1025}
SMTP_USER=${SMTP_USER:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-noreply@manttoai.local}
SMTP_TO_EMAIL=${SMTP_TO_EMAIL:-alertas@manttoai.local}
SMTP_USE_STARTTLS=${SMTP_USE_STARTTLS:-false}
SMTP_REQUIRE_AUTH=${SMTP_REQUIRE_AUTH:-false}
ENABLE_API_DOCS=${ENABLE_API_DOCS:-true}
ENABLE_PREDICTION_SCHEDULER=${ENABLE_PREDICTION_SCHEDULER:-true}
PREDICTION_INTERVAL_SECONDS=${PREDICTION_INTERVAL_SECONDS:-30}
PREDICTION_SCHEDULER_MAX_WORKERS=${PREDICTION_SCHEDULER_MAX_WORKERS:-4}
ML_AUTO_TRAIN_ON_MISSING=${ML_AUTO_TRAIN_ON_MISSING:-true}
SEED_ADMIN_NAME=${SEED_ADMIN_NAME:-Admin ManttoAI}
SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-admin@manttoai.local}
SEED_ADMIN_PASSWORD=${LOCAL_SEED_ADMIN_PASSWORD}
SEED_RESET_ADMIN_PASSWORD=${SEED_RESET_ADMIN_PASSWORD:-false}
SEED_TECNICO_NAME=${SEED_TECNICO_NAME:-Tecnico ManttoAI}
SEED_TECNICO_EMAIL=${SEED_TECNICO_EMAIL:-tecnico@manttoai.local}
SEED_TECNICO_PASSWORD=${LOCAL_SEED_TECNICO_PASSWORD}
SEED_RESET_TECNICO_PASSWORD=${SEED_RESET_TECNICO_PASSWORD:-false}
SEED_DEMO_NAME=${SEED_DEMO_NAME:-Demo ManttoAI}
SEED_DEMO_EMAIL=${SEED_DEMO_EMAIL:-demo@manttoai.local}
SEED_DEMO_PASSWORD=${LOCAL_SEED_DEMO_PASSWORD}
SEED_RESET_DEMO_PASSWORD=${SEED_RESET_DEMO_PASSWORD:-false}
SEED_ALLOW_NON_DEV=${SEED_ALLOW_NON_DEV:-false}
EOF
}

if [ ! -f "$ROOT_ENV_FILE" ]; then
  create_root_env
fi

if [ ! -f "$BACKEND_ENV_FILE" ]; then
  create_backend_env
fi

ensure_env_key "$ROOT_ENV_FILE" "MYSQL_ROOT_PASSWORD" "$LOCAL_MYSQL_PASSWORD"
ensure_env_key "$ROOT_ENV_FILE" "MYSQL_DATABASE" "${MYSQL_DATABASE:-manttoai_db}"
ensure_env_key "$ROOT_ENV_FILE" "MQTT_USERNAME" "${MQTT_USERNAME:-manttoai_mqtt}"
ensure_env_key "$ROOT_ENV_FILE" "MQTT_PASSWORD" "$LOCAL_MQTT_PASSWORD"
ensure_env_key "$ROOT_ENV_FILE" "SECRET_KEY" "$LOCAL_SECRET_KEY"
ensure_env_key "$ROOT_ENV_FILE" "REDIS_PASSWORD" "$LOCAL_REDIS_PASSWORD"
ensure_env_key "$ROOT_ENV_FILE" "SEED_ADMIN_PASSWORD" "$LOCAL_SEED_ADMIN_PASSWORD"
ensure_env_key "$ROOT_ENV_FILE" "SEED_TECNICO_PASSWORD" "$LOCAL_SEED_TECNICO_PASSWORD"
ensure_env_key "$ROOT_ENV_FILE" "SEED_DEMO_PASSWORD" "$LOCAL_SEED_DEMO_PASSWORD"
ensure_env_key "$ROOT_ENV_FILE" "COMPOSE_PROJECT_NAME" "${COMPOSE_PROJECT_NAME:-manttoai}"

ensure_env_key "$BACKEND_ENV_FILE" "MQTT_USERNAME" "${MQTT_USERNAME:-manttoai_mqtt}"
ensure_env_key "$BACKEND_ENV_FILE" "MQTT_PASSWORD" "$LOCAL_MQTT_PASSWORD"
ensure_env_key "$BACKEND_ENV_FILE" "SIMULATOR_ENABLED" "${SIMULATOR_ENABLED:-false}"
ensure_env_key "$BACKEND_ENV_FILE" "ENABLE_API_DOCS" "${ENABLE_API_DOCS:-true}"
ensure_env_key "$BACKEND_ENV_FILE" "PREDICTION_SCHEDULER_MAX_WORKERS" "${PREDICTION_SCHEDULER_MAX_WORKERS:-4}"
ensure_env_key "$BACKEND_ENV_FILE" "SEED_ADMIN_PASSWORD" "$LOCAL_SEED_ADMIN_PASSWORD"
ensure_env_key "$BACKEND_ENV_FILE" "SEED_TECNICO_PASSWORD" "$LOCAL_SEED_TECNICO_PASSWORD"
ensure_env_key "$BACKEND_ENV_FILE" "SEED_DEMO_PASSWORD" "$LOCAL_SEED_DEMO_PASSWORD"

printf 'Entorno local listo: %s y %s\n' "$ROOT_ENV_FILE" "$BACKEND_ENV_FILE"
